language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
#before_script:
 # - npm install -g gulp
script:
  - hexo g
  - hexo algolia
after_script:
  - cd ./public
  - git init
  - git config user.name "RyanNiu"
  - git config user.email "Ryan4work@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - Blogsource
env:
 global:
   - GH_REF: github.com/RyanNiu/RyanNiu.github.io.git
