language: node_js
node_js: stable
# S: Build Lifecycle
install:
 - npm install hexo -g
 - npm install hexo-cli -g
 - npm install hexo-deployer-git -g
 - npm install
script:
  - hexo clean
  - hexo g
  - hexo algolia
after_script:
  - cd ./public
  - git init
  - git config user.name "RyanNiu"
  - git config user.email "Ryan4work@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/RyanNiu/RyanNiu.github.io.git
